import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {createSystemAction} from '../src/system-actions.js';
let mf,db;const key='test-only-not-a-real-secret-123456789';const gatewayKey='test-only-gateway-secret-123456789012345';
const url='https://trinity.test';
async function req(path,body,auth=true,extra={}){return mf.dispatchFetch(url+path,{method:body===undefined?'GET':'POST',headers:{...(auth?{Authorization:'Bearer '+key}:{}),...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},body:body===undefined?undefined:JSON.stringify(body)});}
before(async()=>{
  const modules=readdirSync('dist').filter(x=>!x.endsWith('.map')&&!x.endsWith('.md')).map(name=>({type:name==='index.js'?'ESModule':'Text',path:resolve('dist',name)}));
  modules.sort((a,b)=>a.type==='ESModule'?-1:b.type==='ESModule'?1:0);
  mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'trinity',modules,compatibilityDate:'2026-10-01',compatibilityFlags:['nodejs_compat'],bindings:{TRINITY_OPS_KEY:key,TRINITY_GATEWAY_KEY:gatewayKey,TRINITY_VAULT_KEY:Buffer.alloc(32,7).toString('base64url')},d1Databases:{DB:'test-db'},r2Buckets:{ARTIFACTS:'test-r2'},
    serviceBindings:{AI:{name:'mock',entrypoint:'MockAI'}},workflows:{OPS_WORKFLOW:{name:'test-workflow',className:'TrinityOperations'}}},
    {name:'mock',modules:true,compatibilityDate:'2026-10-01',script:`import {WorkerEntrypoint} from 'cloudflare:workers'; export class MockAI extends WorkerEntrypoint{async run(model,args){if(model.includes('flux'))return {image:btoa('mock-jpeg')};const prompt=args.messages.at(-1).content;if(prompt==='FAIL_TEST')throw new Error('Simulated failure');if(prompt.includes('STUDIO_TEST')){const revised=prompt.includes('STUDIO_TEST_REVISION');return {response:'<!doctype html><html><head><title>Studio test</title></head><body><main><h1>'+(revised?'Revised':'Created')+'</h1></main></body></html>'};}return {response:'TEST_MODEL_RESULT'};}} export default {fetch(){return new Response('mock')}};`} ]}));
  db=await mf.getD1Database('DB','trinity');
  await db.batch([
    db.prepare('CREATE TABLE memory(id TEXT PRIMARY KEY,content TEXT)'),
    db.prepare('CREATE TABLE knowledge(id INTEGER PRIMARY KEY,topic TEXT,content TEXT)'),
    db.prepare('CREATE TABLE personality(id INTEGER PRIMARY KEY,trait TEXT,value TEXT)'),
    db.prepare('CREATE TABLE notes(id TEXT PRIMARY KEY,title TEXT,content TEXT)'),
    db.prepare('CREATE TABLE memory_long(key TEXT,value TEXT,category TEXT,importance INTEGER)'),
    db.prepare('CREATE TABLE projects(id TEXT,name TEXT,description TEXT,status TEXT,updated_at TEXT)'),
    db.prepare('CREATE TABLE tasks(id TEXT,title TEXT,status TEXT,assigned_agent TEXT,updated_at TEXT)'),
    db.prepare("INSERT INTO memory(id,content) VALUES('old-1','Používateľ má rád stručné odpovede.'),('unsafe-1','api key secret must not migrate')"),
    db.prepare("INSERT INTO personality(id,trait,value) VALUES(1,'tone','srdečný')")
  ]);
  for(const file of readdirSync('migrations').filter(f=>f.endsWith('.sql')).sort()){
    const sql=readFileSync('migrations/'+file,'utf8');await db.batch(sql.split(/;\s*(?:\r?\n|$)/).map(s=>s.trim()).filter(Boolean).map(s=>db.prepare(s)));
  }
});
after(async()=>{await mf?.dispose();});
test('public UI and health, private APIs',async()=>{assert.equal((await req('/',undefined,false)).status,200);assert.equal((await (await req('/health',undefined,false)).json()).agents,40);assert.equal((await req('/api/ops/agents',undefined,false)).status,401);assert.equal((await req('/mcp',{},false)).status,401);});
test('login sets protected cookie and logout revokes it',async()=>{const r=await req('/api/ops/login',{key},false);assert.equal(r.status,200);const c=r.headers.get('set-cookie');assert.match(c,/HttpOnly/);assert.match(c,/Secure/);assert.match(c,/SameSite=Strict/);assert.equal((await req('/api/ops/status',undefined,false,{Cookie:c.split(';')[0]})).status,200);await req('/api/ops/logout',{},false,{Cookie:c.split(';')[0]});assert.equal((await req('/api/ops/status',undefined,false,{Cookie:c.split(';')[0]})).status,401);});
test('Google auth stays dormant and the authenticated owner is recognized',async()=>{const config=await(await req('/api/auth/config',undefined,false)).json();assert.deepEqual(config,{google_enabled:false,google_required:false});assert.equal((await req('/api/auth/google/start',undefined,false)).status,404);const pending=await req('/api/ops/users/pending');assert.equal(pending.status,200);assert.equal((await req('/api/ops/users/example%40gmail.com/approve',{})).status,404);});
test('owner emergency stop pauses work and can resume it',async()=>{const before=await(await req('/api/ops/control')).json();assert.equal(before.emergency_stop,false);const stopped=await(await req('/api/ops/control',{emergency_stop:true,reason:'runtime test'})).json();assert.equal(stopped.emergency_stop,true);assert.equal((await req('/api/ops/jobs',{task:'blocked while stopped'})).status,503);const status=await(await req('/api/ops/status')).json();assert.equal(status.control.emergency_stop,true);const resumed=await(await req('/api/ops/control',{emergency_stop:false,reason:'runtime test complete'})).json();assert.equal(resumed.emergency_stop,false);});
test('origin validation and unknown agent',async()=>{assert.equal((await req('/api/ops/jobs',{task:'hi'},true,{Origin:'https://evil.test'})).status,403);assert.equal((await req('/api/ops/jobs',{task:'hi',agent:'not-real'})).status,400);});
test('memory persists and parameterized queries resist SQL injection',async()=>{assert.equal((await req('/api/ops/memory',{key:'unit-memory',value:'unique-verified-value'})).status,200);const r=await(await req('/api/ops/memory?q=unique-verified-value')).json();assert.equal(r.records[0].value,'unique-verified-value');assert.equal((await req('/api/ops/memory?q='+encodeURIComponent("';DROP TABLE ops_jobs;--"))).status,200);assert.equal((await req('/api/ops/jobs')).status,200);});
test('legacy memories migrate without credential-like records',async()=>{const safe=await(await req('/api/ops/memory?q='+encodeURIComponent('stručné odpovede'))).json();assert.ok(safe.records.some(r=>r.source==='legacy:memory'));const unsafe=await(await req('/api/ops/memory?q='+encodeURIComponent('must not migrate'))).json();assert.equal(unsafe.records.length,0);const identity=await(await req('/api/ops/memory?q='+encodeURIComponent('jednu osobnú asistentku'))).json();assert.ok(identity.records.some(r=>r.key==='profil/trinity-identita'));});
test('persistent personality and truth profile are available',async()=>{const personality=await(await req('/api/ops/memory?q='+encodeURIComponent('nepredstiera biologické emócie'))).json();assert.ok(personality.records.some(r=>r.key==='profil/trinity-osobnost'));const status=await(await req('/api/assistant/status')).json();assert.equal(status.consciousness,false);assert.equal(status.truth_mode,'evidence-required');assert.equal(status.personality,'persistent');});
test('main dashboard exposes builder, visible account state, and admin control panels but not hidden system tools',async()=>{const dashboard=await(await req('/api/assistant/dashboard')).json();assert.equal(typeof dashboard.today_completed,'number');assert.equal(typeof dashboard.memory_count,'number');assert.ok(Array.isArray(dashboard.recent_jobs));const html=await(await req('/',undefined,false)).text();assert.match(html,/dashboard-view/);assert.match(html,/AI Studio/);assert.match(html,/studio-preview/);assert.match(html,/studio-tab-code/);assert.match(html,/studio-tab-quality/);assert.match(html,/settings-search/);assert.match(html,/settings-default-engine/);assert.match(html,/account-state/);assert.match(html,/settings-account-status/);assert.match(html,/settings-view/);assert.match(html,/settings-integrations/);assert.match(html,/api-key-form/);assert.match(html,/secret-form/);assert.match(html,/settings-wallet-panel/);assert.match(html,/settings-users-panel/);assert.doesNotMatch(html,/request_system_action|selfwrite/);});
test('AI Studio creates, previews, revises, lists, and exports a versioned website',async()=>{
  const createdResponse=await req('/api/assistant/studio/projects',{prompt:'STUDIO_TEST create a modern website'});const createdText=await createdResponse.text();assert.equal(createdResponse.status,201,createdText);const created=JSON.parse(createdText).project;
  assert.equal(created.version,1);assert.match(created.html,/Content-Security-Policy/i);assert.match(created.html,/>Created</);assert.equal(created.versions.length,1);
  const listed=await(await req('/api/assistant/studio/projects')).json();assert.ok(listed.items.some(item=>item.id===created.id));
  const revised=await(await req('/api/assistant/studio/projects/'+created.id+'/revise',{prompt:'STUDIO_TEST_REVISION make the hero clearer'})).json();assert.equal(revised.project.version,2);assert.match(revised.project.html,/>Revised</);assert.equal(revised.project.versions.length,2);
  const exported=await req('/api/assistant/studio/projects/'+created.id+'/export');assert.equal(exported.status,200);assert.match(exported.headers.get('content-disposition'),/attachment/);assert.match(await exported.text(),/Content-Security-Policy/i);
});
test('required plugins are actually installed and enabled',async()=>{const plugins=await(await req('/api/ops/plugins')).json();assert.equal(plugins.length,24);assert.ok(plugins.every(p=>p.installed&&p.enabled));assert.ok(plugins.some(p=>p.id==='truth'&&p.required));assert.ok(plugins.some(p=>p.id==='clock'&&p.tools.includes('current_time')));assert.ok(plugins.some(p=>p.id==='skills'&&p.tools.includes('list_skills')));assert.ok(plugins.some(p=>p.id==='connectors'&&p.tools.includes('list_connectors')));assert.ok(plugins.some(p=>p.id==='images'&&p.tools.includes('generate_image')));assert.ok(plugins.some(p=>p.id==='trading'&&p.tools.includes('portfolio_summary')));assert.ok(plugins.some(p=>p.id==='computer-control'&&p.required&&p.tools.includes('pc_app_control')));assert.ok(plugins.some(p=>p.id==='workspace-files'&&p.required&&p.tools.includes('pc_file_write')));assert.ok(plugins.some(p=>p.id==='internet-operator'&&p.required&&p.tools.includes('pc_web_fetch')));assert.ok(plugins.some(p=>p.id==='developer-operator'&&p.required&&p.tools.includes('pc_run')));});
test('trusted plugin install restores a built-in module and rejects unknown code',async()=>{await req('/api/ops/plugins/skills',{enabled:false});const installed=await req('/api/ops/plugins/skills/install',{});assert.equal(installed.status,201);assert.equal((await installed.json()).enabled,true);assert.equal((await req('/api/ops/plugins/untrusted/install',{})).status,404);});
test('settings can toggle optional modules but protect required security modules',async()=>{const settings=await(await req('/api/assistant/settings')).json();assert.equal(settings.version,'8.9.0');assert.equal(settings.plugins.length,24);assert.equal(settings.permissions.manage_api_keys,true);assert.equal(settings.permissions.manage_secrets,true);assert.equal(settings.permissions.manage_trading,true);assert.equal((await req('/api/assistant/settings/plugins/truth',{enabled:false})).status,400);assert.equal((await req('/api/assistant/settings/plugins/computer-control',{enabled:false})).status,400);let changed=await(await req('/api/assistant/settings/plugins/clock',{enabled:false})).json();assert.equal(changed.enabled,false);changed=await(await req('/api/assistant/settings/plugins/clock',{enabled:true})).json();assert.equal(changed.enabled,true);});
test('declarative API builder creates and invokes an authenticated JSON API',async()=>{const createdResponse=await req('/api/assistant/apis',{name:'Test status',slug:'test-status',method:'GET',response:{ok:true,service:'Trinity'},status:'active'});assert.equal(createdResponse.status,201,await createdResponse.clone().text());const created=(await createdResponse.json()).api;const invoked=await req('/api/assistant/apis/'+created.id+'/invoke');assert.equal(invoked.status,200);assert.deepEqual(await invoked.json(),{ok:true,service:'Trinity'});});
test('Trinity API keys expose the secret once, invoke scoped APIs, and revoke cleanly',async()=>{const createdResponse=await req('/api/assistant/api-keys',{name:'Runtime client',scopes:['api:invoke'],rate_limit_per_minute:30,expires_at:null});assert.equal(createdResponse.status,201,await createdResponse.clone().text());const created=(await createdResponse.json()).key;assert.match(created.secret,/^trn_live_[A-Za-z0-9_-]{43}$/);assert.equal(created.secret_visible_once,true);const listed=await(await req('/api/assistant/api-keys')).json();const item=listed.items.find(row=>row.id===created.id);assert.ok(item);assert.equal(item.secret,undefined);assert.equal(item.key_hash,undefined);const invoked=await mf.dispatchFetch(url+'/api/v1/generated/test-status',{headers:{Authorization:'Bearer '+created.secret}});assert.equal(invoked.status,200,await invoked.clone().text());assert.deepEqual(await invoked.json(),{ok:true,service:'Trinity'});const rejected=await mf.dispatchFetch(url+'/api/v1/generated/test-status',{headers:{Authorization:'Bearer trn_live_'+'x'.repeat(43)}});assert.equal(rejected.status,401);const revoked=await req('/api/assistant/api-keys/'+created.id+'/revoke',{});assert.equal(revoked.status,200,await revoked.clone().text());const after=await mf.dispatchFetch(url+'/api/v1/generated/test-status',{headers:{Authorization:'Bearer '+created.secret}});assert.equal(after.status,401);});
test('encrypted vault never returns a stored secret',async()=>{const storedResponse=await req('/api/assistant/secrets',{provider:'custom',name:'Runtime secret',secret:'super-secret-runtime-value'});assert.equal(storedResponse.status,201,await storedResponse.clone().text());const stored=(await storedResponse.json()).item;assert.equal(stored.secret,undefined);assert.match(stored.secret_hint,/••••alue/);const listed=await(await req('/api/assistant/secrets')).json();assert.equal(JSON.stringify(listed).includes('super-secret-runtime-value'),false);assert.equal((await req('/api/assistant/secrets/'+stored.id+'/verify',{})).status,400);assert.equal((await req('/api/assistant/secrets/'+stored.id+'/revoke',{})).status,200);});
test('Gemini provider requires an encrypted and verified credential before activation',async()=>{const providers=await(await req('/api/assistant/ai-providers')).json();assert.equal(providers.items.find(item=>item.id==='gemini').configured,false);const stored=await(await req('/api/assistant/secrets',{provider:'gemini',name:'Runtime Gemini',secret:'runtime-gemini-api-key'})).json();const configured=await req('/api/assistant/ai-providers/gemini',{secret_id:stored.item.id,model:'models/gemini-test',enabled:true});assert.equal(configured.status,409);assert.equal(JSON.stringify(await(await req('/api/assistant/secrets')).json()).includes('runtime-gemini-api-key'),false);});
test('Gemini project control exposes every bounded action but keeps owner approval',async()=>{const stored=await(await req('/api/assistant/secrets',{provider:'gemini',name:'Runtime Gemini Control',secret:'runtime-gemini-control-key'})).json();await db.prepare("UPDATE ops_secret_vault SET status='verified',verification_json=? WHERE id=?").bind(JSON.stringify({models:['models/gemini-test']}),stored.item.id).run();const response=await req('/api/assistant/ai-providers/gemini',{secret_id:stored.item.id,model:'models/gemini-test',enabled:true,project_control:true});assert.equal(response.status,200,await response.clone().text());const configured=(await response.json()).item;assert.equal(configured.project_control,true);assert.equal(configured.approval_policy,'owner-required');const listed=await(await req('/api/assistant/ai-providers')).json();const gemini=listed.items.find(item=>item.id==='gemini');assert.equal(gemini.project_control,true);assert.equal(gemini.approval_policy,'owner-required');assert.deepEqual(gemini.allowed_actions,['read','write','edit','selfwrite','run','deploy','share','upload','upgrade']);});
test('provider diagnostics persist a safe last-check receipt for Settings',async()=>{const tested=await req('/api/ops/providers/test',{provider:'workers-ai'});assert.equal(tested.status,200,await tested.clone().text());const receipt=await tested.json();assert.equal(receipt.status,'verified');assert.equal(receipt.provider,'workers-ai');assert.ok(receipt.latency_ms>=0);const providers=await(await req('/api/assistant/ai-providers')).json();const workers=providers.items.find(item=>item.id==='workers-ai');assert.equal(workers.last_check.status,'verified');assert.equal(workers.last_check.error,null);assert.equal(JSON.stringify(workers).includes(key),false);});
test('admin wallet simulates deposits and payments without real money',async()=>{let wallet=await(await req('/api/assistant/wallet',{type:'deposit',amount:20,note:'runtime'})).json();assert.equal(wallet.balance,20);assert.equal(wallet.real_money,false);wallet=await(await req('/api/assistant/wallet',{type:'send',amount:5,recipient:'Test recipient'})).json();assert.equal(wallet.balance,15);assert.equal(wallet.transactions[0].status,'simulated');assert.equal((await req('/api/assistant/wallet',{type:'withdrawal',amount:100})).status,409);});
test('paper portfolio records simulated trades and rejects overselling',async()=>{const createdResponse=await req('/api/assistant/trading/portfolios',{name:'Runtime paper',base_currency:'EUR',starting_cash:10000,max_position_pct:20,max_drawdown_pct:15});assert.equal(createdResponse.status,201,await createdResponse.clone().text());const portfolio=await createdResponse.json();const bought=await req(`/api/assistant/trading/portfolios/${portfolio.id}/trades`,{symbol:'TEST',asset_type:'stock',side:'buy',quantity:10,price:100,fee:5,executed_at:'2026-10-06T10:00:00Z',thesis:'runtime',source:'test'});assert.equal(bought.status,201,await bought.clone().text());assert.equal((await bought.json()).summary.equity,9995);const quote=await req('/api/assistant/trading/quotes',{symbol:'TEST',currency:'EUR',price:110,as_of:'2026-10-06T11:00:00Z',source:'test'});assert.equal(quote.status,200);const read=await(await req('/api/assistant/trading/portfolios/'+portfolio.id)).json();assert.equal(read.summary.equity,10095);assert.equal(read.summary.paper_only,true);const oversell=await req(`/api/assistant/trading/portfolios/${portfolio.id}/trades`,{symbol:'TEST',asset_type:'stock',side:'sell',quantity:11,price:110,fee:0,executed_at:'2026-10-06T12:00:00Z',thesis:'runtime',source:'test'});assert.equal(oversell.status,409);});
test('image plugin creates and serves a private image artifact',async()=>{const result=await(await req('/api/ops/plugins/images/test',{})).json();assert.equal(result.status,'verified');assert.match(result.details.url,/\/api\/assistant\/media\/images\//);const image=await req(result.details.url);assert.equal(image.status,200);assert.match(image.headers.get('content-type'),/image\/jpeg/);});
test('authenticated admin commands execute directly while agent proposals still require approval',async()=>{
  assert.equal((await req('/api/system/capabilities',undefined,false)).status,401);
  const untrusted=await createSystemAction({DB:db},{action:'write',payload:{path:'Trinity/untrusted.txt',content:'no'},rationale:'agent proposal test'},'agent:trinity',{adminAuthorized:true});
  assert.equal(untrusted.status,'proposed');
  const createResponse=await req('/api/system/actions',{action:'write',payload:{path:'Trinity/example.txt',expected_sha256:'absent',content:'hello'},rationale:'runtime test'});const createText=await createResponse.text();assert.equal(createResponse.status,201,createText);const created=JSON.parse(createText);
  assert.equal(created.action.status,'approved');assert.match(created.action.approved_by,/^admin:user:/);const id=created.action.id;
  let claim=await(await req('/api/system/actions/claim',{},false,{Authorization:'Bearer '+gatewayKey})).json();assert.equal(claim.action.id,id);assert.equal(claim.action.status,'claimed');
  const receipt={action:'write',path:'Trinity/example.txt',after_sha256:'abc'};
  const finished=await(await req(`/api/system/actions/${id}/receipt`,{status:'completed',receipt},false,{Authorization:'Bearer '+gatewayKey})).json();assert.equal(finished.action.status,'completed');assert.deepEqual(finished.action.receipt,receipt);
});
test('expired claimed actions are closed as failed instead of remaining stuck',async()=>{const created=await(await req('/api/system/actions',{action:'read',payload:{path:'Trinity/package.json'},rationale:'expiry recovery test'})).json();await db.prepare("UPDATE ops_system_actions SET status='claimed',claimed_by='old-gateway',lease_until=0,expires_at=0 WHERE id=?").bind(created.action.id).run();const claim=await(await req('/api/system/actions/claim',{},false,{Authorization:'Bearer '+gatewayKey})).json();assert.equal(claim.action,null);const recovered=await(await req('/api/system/actions/'+created.action.id)).json();assert.equal(recovered.action.status,'failed');assert.match(recovered.action.error,/vypršala/);});
test('durable job completes, stores artifact, and deduplicates',async()=>{const data={task:'Runtime verification',team:['planner','writer','qa'],idempotency_key:crypto.randomUUID()};const r=await req('/api/ops/jobs',data);assert.equal(r.status,202);const job=await r.json();const duplicate=await(await req('/api/ops/jobs',data)).json();assert.equal(duplicate.id,job.id);assert.equal(duplicate.reused,true);let done;for(let i=0;i<100;i++){done=await(await req('/api/ops/jobs/'+job.id)).json();if(['completed','failed'].includes(done.status))break;await new Promise(r=>setTimeout(r,200));}assert.equal(done.status,'completed',JSON.stringify(done));assert.equal(done.steps.length,3);assert.equal(done.result,'TEST_MODEL_RESULT');const artifact=await req('/api/ops/jobs/'+job.id+'/artifact');assert.equal(artifact.status,200);assert.match(await artifact.text(),/TEST_MODEL_RESULT/);});
test('MCP initializes and exposes five working tools',async()=>{const headers={Accept:'application/json, text/event-stream'};const r=await req('/mcp',{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'test',version:'1'}}},true,headers);assert.equal(r.status,200,await r.clone().text());const list=await req('/mcp',{jsonrpc:'2.0',id:2,method:'tools/list',params:{}},true,headers);const text=await list.text();assert.equal(list.status,200,text);assert.match(text,/dispatch_task/);assert.match(text,/search_memory/);const call=await req('/mcp',{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'list_agents',arguments:{}}},true,headers);assert.equal(call.status,200);assert.match(await call.text(),/orchestrator/);});

