import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AGENTS,selectTeam,shouldDelegate} from '../src/registry.js';
import {validKey,checkOrigin,readJSON} from '../src/security.js';
import {jobSchema} from '../src/jobs.js';
import {parseAction,runAgent} from '../src/engine.js';
import {runTool} from '../src/tools.js';
import {getOllamaKey,serviceStatus} from '../src/services.js';
import {TRUTH_POLICY,findUnsupportedActionClaims,truthStatus} from '../src/truth.js';
test('40 unique agents in eight departments',()=>{assert.equal(AGENTS.length,40);assert.equal(new Set(AGENTS.map(a=>a.id)).size,40);assert.equal(new Set(AGENTS.map(a=>a.cluster)).size,8);});
test('routing and team deduplication',()=>{assert.deepEqual(selectTeam('Cloudflare binding','team'),['planner','cloudflare','qa','orchestrator']);assert.equal(selectTeam('test','team','orchestrator').length,3);});
test('work requests delegate while ordinary conversation stays direct',()=>{assert.equal(shouldDelegate('Ahoj Trinity'),false);assert.equal(shouldDelegate('Oprav a otestuj Cloudflare Worker'),true);assert.ok(AGENTS.find(a=>a.id==='orchestrator').tools.includes('web_search'));});
test('fail closed and exact secret comparison',async()=>{assert.equal(await validKey('x',{}),false);assert.equal(await validKey('a'.repeat(32),{TRINITY_OPS_KEY:'b'.repeat(32)}),false);assert.equal(await validKey('a'.repeat(32),{TRINITY_OPS_KEY:'a'.repeat(32)}),true);});
test('cross-origin blocked',()=>assert.throws(()=>checkOrigin(new Request('https://trinity.test/api',{headers:{Origin:'https://evil.test'}})),{status:403}));
test('bad JSON and oversized bodies rejected',async()=>{await assert.rejects(readJSON(new Request('http://localhost',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'})),{status:400});await assert.rejects(readJSON(new Request('http://localhost',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'.repeat(25000)})),{status:413});});
test('job input rejects empty task and excessive teams',()=>{assert.equal(jobSchema.safeParse({task:' '}).success,false);assert.equal(jobSchema.safeParse({task:'hello',team:Array(6).fill('qa')}).success,false);});
test('device keys cannot masquerade as Ollama API keys',async()=>assert.rejects(getOllamaKey({OLLAMA_API_KEY:'ssh-ed25519 public'})));
test('tool allowlist rejects arbitrary execution',async()=>assert.rejects(runTool({},AGENTS[0],'shell',{command:'whoami'})));
test('actual inference result, not placeholder',async()=>{const result=await runAgent({AI:{run:async()=>({response:'Overená skúšobná odpoveď'})}},'writer','Napíš vetu');assert.equal(result.text,'Overená skúšobná odpoveď');assert.equal(result.agent_id,'writer');});
test('structured Workers AI response is normalized',async()=>{const result=await runAgent({AI:{run:async()=>({response:{answer:'Štruktúrovaná odpoveď'}})}},'writer','Napíš vetu');assert.equal(result.text,'Štruktúrovaná odpoveď');});
test('model failure propagates',async()=>assert.rejects(runAgent({AI:{run:async()=>{throw new Error('model unavailable')}}},'writer','hello'),/model unavailable/));
test('tool requests parse safely',()=>{assert.equal(parseAction('plain text').answer,'plain text');assert.equal(parseAction('```json\n{"tool":"search_memory","arguments":{}}\n```').tool,'search_memory');});
test('health check does not claim inference success',async()=>{const rows=await serviceStatus({CORE:{fetch:async()=>Response.json({ok:true})}},'CORE');assert.equal(rows[0].status,'reachable');assert.match(rows[0].note,/nepotvrdzuje/);});
test('truth policy rejects consciousness claims and requires evidence',()=>{assert.match(TRUTH_POLICY,/Nemáš preukázané vedomie/);assert.match(TRUTH_POLICY,/potvrdená dôveryhodným systémovým záznamom/);});
test('unsupported external action claims are detected',()=>{assert.deepEqual(findUnsupportedActionClaims('Nasadila som nový Worker.',[]),['deploy']);assert.deepEqual(findUnsupportedActionClaims('I uploaded the file.',[]),['publish']);assert.equal(truthStatus('Pripravila som návrh.',[]).status,'passed');});
test('verified read receipt supports a verification statement',()=>{const receipt={tool:'service_status',status:'completed',effect:'read',receipt_id:'receipt-1'};assert.deepEqual(findUnsupportedActionClaims('Overila som dostupnosť služby.',[receipt]),[]);});
test('agent rewrites an unsupported action claim before returning it',async()=>{let calls=0;const env={AI:{run:async()=>({response:++calls===1?'Nasadila som Worker.':'Nemám overený dôkaz, že bol Worker nasadený.'})}};const result=await runAgent(env,'writer','Nasadila si Worker?');assert.equal(calls,2);assert.match(result.text,/Nemám overený dôkaz/);assert.equal(result.truth.status,'passed');});
test('all Trinity roles can use the installed clock and capability catalog',()=>{assert.ok(AGENTS.every(a=>a.tools.includes('current_time')&&a.tools.includes('list_capabilities')));});
test('only the single orchestrator receives hidden system proposal tools',()=>{assert.ok(AGENTS.find(a=>a.id==='orchestrator').tools.includes('request_system_action'));assert.ok(AGENTS.filter(a=>a.id!=='orchestrator').every(a=>!a.tools.includes('request_system_action')));});
test('completed system receipt supports only its mapped mutation claims',()=>{const receipt={tool:'system_action_status',status:'completed',effect:'mutation',actions:['deploy'],receipt_id:'action-1'};assert.deepEqual(findUnsupportedActionClaims('Nasadila som nový Worker.',[receipt]),[]);assert.deepEqual(findUnsupportedActionClaims('Nainštalovala som balík.',[receipt]),['install']);});
