import {z} from 'zod';
import {HttpError} from './security.js';
const slug=z.string().trim().min(2).max(60).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
export const apiDefinitionSchema=z.object({name:z.string().trim().min(2).max(100),slug,description:z.string().trim().max(500).default(''),method:z.enum(['GET','POST']).default('GET'),response:z.json(),status:z.enum(['draft','active','disabled']).default('draft')}).strict();
function decode(row){if(!row)return null;const {response_json,...rest}=row;return {...rest,response:JSON.parse(response_json)};}
export async function listApis(env,ownerId){const rows=await env.DB.prepare('SELECT * FROM ops_api_definitions WHERE owner_id=? ORDER BY updated_at DESC LIMIT 100').bind(ownerId).all();return rows.results.map(decode);}
export async function createApi(env,ownerId,input){const data=apiDefinitionSchema.parse(input),id=crypto.randomUUID();try{const row=await env.DB.prepare(`INSERT INTO ops_api_definitions(id,owner_id,name,slug,description,method,response_json,status) VALUES(?,?,?,?,?,?,?,?) RETURNING *`).bind(id,ownerId,data.name,data.slug,data.description,data.method,JSON.stringify(data.response),data.status).first();return decode(row);}catch(error){if(String(error?.message||'').includes('UNIQUE'))throw new HttpError(409,'API s týmto názvom cesty už existuje.');throw error;}}
export async function invokeApi(env,ownerId,id,method){const row=await env.DB.prepare('SELECT * FROM ops_api_definitions WHERE id=? AND owner_id=?').bind(id,ownerId).first();if(!row)throw new HttpError(404,'API neexistuje.');if(row.status!=='active')throw new HttpError(409,'API ešte nie je aktívne.');if(row.method!==method)throw new HttpError(405,`Táto API cesta vyžaduje metódu ${row.method}.`);await env.DB.prepare('INSERT INTO ops_api_invocations(id,api_id,owner_id,request_method,status_code) VALUES(?,?,?,?,200)').bind(crypto.randomUUID(),id,ownerId,method).run();return JSON.parse(row.response_json);}
export async function invokeApiBySlug(env,ownerId,slug,method){const row=await env.DB.prepare("SELECT * FROM ops_api_definitions WHERE owner_id=? AND slug=? AND status='active'").bind(ownerId,slug).first();if(!row)throw new HttpError(404,'Aktívna API cesta neexistuje.');return invokeApi(env,ownerId,row.id,method);}
