export const PLUGINS=[
 {id:'memory',name:'Pamäť',icon:'◈',description:'Ukladá tvoje poznámky a pripomína relevantné informácie pred odpoveďou.',tools:['search_memory'],dependency:'Cloudflare D1',version:'1.1.0'},
 {id:'projects',name:'Projekty',icon:'▦',description:'Číta existujúce projekty a úlohy. Nepredstiera ich dokončenie.',tools:['project_snapshot'],dependency:'Cloudflare D1',version:'1.0.0'},
 {id:'web',name:'Webový výskum',icon:'◎',description:'Vyhľadáva aktuálne zdroje cez overený účet Ollama.',tools:['web_search'],dependency:'Ollama API',version:'1.0.0'},
 {id:'images',name:'Tvorba obrázkov',icon:'◉',description:'Generuje skutočné obrázky pomocou Workers AI a bezpečne ich ukladá do R2.',tools:['generate_image'],dependency:'Workers AI + R2',version:'1.0.0'},
 {id:'monitor',name:'Strážca služieb',icon:'⌁',description:'Overuje dostupnosť existujúcich služieb Trinity.',tools:['service_status'],dependency:'Service bindings',version:'1.0.0'},
 {id:'calculator',name:'Presné výpočty',icon:'±',description:'Počíta súčet, rozdiel, súčin, podiel, percentá a priemer. Bez spúšťania cudzieho kódu.',tools:['calculate'],dependency:'Lokálny výpočet vo Workeri',version:'1.0.0'},
 {id:'text',name:'Analýza textu',icon:'Aa',description:'Spočíta znaky, slová, vety a odhadne čas čítania.',tools:['analyze_text'],dependency:'Lokálny výpočet vo Workeri',version:'1.0.0'},
 {id:'clock',name:'Čas a dátum',icon:'◷',description:'Vráti skutočný čas pre zadané časové pásmo.',tools:['current_time'],dependency:'Worker runtime',version:'1.0.0'},
 {id:'capabilities',name:'Katalóg schopností',icon:'◇',description:'Ukáže nainštalované a zapnuté moduly jednej Trinity.',tools:['list_capabilities'],dependency:'Plugin registry',version:'1.0.0'},
 {id:'truth',name:'Strážca pravdivosti',icon:'✓',description:'Blokuje nepodložené tvrdenia o vykonaných akciách a oddeľuje fakty od návrhov.',tools:[],dependency:'Truth policy + evidence receipts',version:'1.0.0',required:true},
 {id:'mcp',name:'MCP most',icon:'↔',description:'Päť nástrojov pre pripojenie Trinity k ďalším AI aplikáciám.',tools:[],dependency:'MCP SDK + Agents SDK',version:'1.0.0'},
 {id:'artifacts',name:'Archív výstupov',icon:'↗',description:'Ukladá dokončené výstupy tímu do stiahnuteľných dokumentov.',tools:[],dependency:'Cloudflare R2',version:'1.0.0',required:true},
 {id:'skills',name:'Zručnosti Trinity',icon:'✳',description:'Poskytuje špecializované pracovné postupy pre vývoj, výskum, prevádzku a bezpečnosť.',tools:['list_skills','install_plugin'],dependency:'Zabudovaný katalóg zručností',version:'1.0.0'},
 {id:'connectors',name:'Konektory',icon:'↔',description:'Zobrazuje dostupné Cloudflare bindings a stav nakonfigurovaných služieb bez odhalenia tajomstiev.',tools:['list_connectors'],dependency:'Cloudflare service bindings',version:'1.0.0'}
 ,{id:'trading',name:'Papierové portfólio',icon:'↗',description:'Číta simulované investičné portfólio, pozície, hotovosť a zisk alebo stratu. Nikdy nevykonáva reálne obchody.',tools:['portfolio_summary'],dependency:'Cloudflare D1',version:'1.0.0'}
 ,{id:'json-data',name:'JSON a dáta',icon:'{}',description:'Bezpečne overuje, formátuje, zmenšuje a číta JSON bez spúšťania kódu.',tools:['json_tool'],dependency:'Worker runtime',version:'1.0.0'}
 ,{id:'checksums',name:'Kontrolné súčty',icon:'#',description:'Vytvára SHA-256 odtlačky textu pre kontrolu integrity.',tools:['hash_text'],dependency:'Web Crypto',version:'1.0.0'}
 ,{id:'units',name:'Prevody jednotiek',icon:'⇄',description:'Presne prevádza bežné jednotky dĺžky, hmotnosti a teploty.',tools:['convert_units'],dependency:'Lokálny výpočet vo Workeri',version:'1.0.0'}
 ,{id:'entities',name:'Extrakcia údajov',icon:'⌕',description:'Vyhľadá v texte URL adresy, e-maily a dátumy bez odoslania dát tretej strane.',tools:['extract_entities'],dependency:'Worker runtime',version:'1.0.0'}
 ,{id:'text-format',name:'Formátovanie textu',icon:'Aa',description:'Vytvára slug, snake_case, kebab-case a ďalšie bezpečné textové formáty.',tools:['format_text'],dependency:'Worker runtime',version:'1.0.0'}
 ,{id:'computer-control',name:'Ovládanie počítača',icon:'⌨',description:'Adminovi umožňuje screenshot, systémové informácie, notifikácie a ovládanie povolených aplikácií cez zabezpečený PC Bridge.',tools:['pc_screenshot','pc_open_app','pc_app_control','pc_notify','pc_system_info'],dependency:'Trinity PC Bridge 2.0',version:'1.0.0',required:true}
 ,{id:'workspace-files',name:'Súbory a pracovný priestor',icon:'▣',description:'Adminovi umožňuje čítať, vytvárať, dopĺňať a upravovať súbory alebo priečinky v povolenom workspace.',tools:['pc_file_read','pc_file_write','pc_file_append','pc_file_edit','pc_directory_create','pc_download'],dependency:'Trinity PC Bridge 2.0',version:'1.0.0',required:true}
 ,{id:'internet-operator',name:'Internetový operátor',icon:'◌',description:'Bezpečne načítava a spracúva verejné HTTP/HTTPS zdroje; blokuje lokálne siete a obmedzuje veľkosť odpovedí.',tools:['pc_web_fetch','pc_scrape'],dependency:'Trinity PC Bridge 2.0 + voliteľný Firecrawl',version:'1.0.0',required:true}
 ,{id:'developer-operator',name:'Vývoj a Git',icon:'</>',description:'Adminovi umožňuje spúšťať príkazy, testy, Git commit a pull request cez auditovaný lokálny Bridge.',tools:['pc_run','pc_git_commit','pc_git_pr'],dependency:'Trinity PC Bridge 2.0 + Git',version:'1.0.0',required:true}
 ,{id:'morpheus-core',name:'Trinity Morpheus Core',icon:'✦',description:'Koordinuje existujúcich agentov Trinity, pripravuje plány úloh a zobrazuje bezpečný stav jadra bez vykonania externých akcií.',tools:['morpheus_core_plan','morpheus_core_status'],dependency:'Trinity orchestrator + agent registry + Cloudflare D1',version:'0.1.0',assistantPluginId:'plugins_6aca349ed67c81919499f513a73bdab5',assistantPluginUrl:'https://chatgpt.com/plugins/plugins_6aca349ed67c81919499f513a73bdab5',integrationMode:'assistant-workflow'}
,
 {id:'trinity-ai-developer',name:"Trinity AI Developer",icon:'✦',description:"Diagnostika chýb, vývoj funkcií a tvorba aplikácií; pracovný postup asistenta, nie samostatný Worker runtime.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"0.1.0",assistantPluginId:"plugins_6aca36322030819190c6ffe2d53f88fb",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca36322030819190c6ffe2d53f88fb",integrationMode:'assistant-workflow'},
 {id:'trinity-architecture-orchestrator',name:"Trinity Architecture Orchestrator",icon:'✦',description:"Návrh architektúry existujúcej Trinity; vyžaduje dôkazy a zachovanie súčasného projektu.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35a9d2248191930fa432bc2dbe70",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35a9d2248191930fa432bc2dbe70",integrationMode:'assistant-workflow'},
 {id:'trinity-repository-investigator',name:"Trinity Repository Investigator",icon:'✦',description:"Analýza repozitára, regresií a zmien; nevykonáva automaticky externé operácie.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35b2a2ac8191a34401d2964bf4ff",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35b2a2ac8191a34401d2964bf4ff",integrationMode:'assistant-workflow'},
 {id:'trinity-build-repair',name:"Trinity Build Repair",icon:'✦',description:"Diagnostika buildov a nasadzovacích pipeline podľa skutočných logov.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35bb920081918f4c718c4cb197fd",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35bb920081918f4c718c4cb197fd",integrationMode:'assistant-workflow'},
 {id:'trinity-security-guardian',name:"Trinity Security Guardian",icon:'✦',description:"Kontrola tajomstiev, oprávnení, autentifikácie a bezpečnostných hraníc.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35c449c881918f4da954f65569f4",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35c449c881918f4da954f65569f4",integrationMode:'assistant-workflow'},
 {id:'trinity-integration-manager',name:"Trinity Integration Manager",icon:'✦',description:"Návrh a overovanie konektorov; samotná registrácia nepotvrdzuje živé pripojenie.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35ccf5008191910467d3c0a59a8d",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35ccf5008191910467d3c0a59a8d",integrationMode:'assistant-workflow'},
 {id:'trinity-quality-gate',name:"Trinity Quality Gate",icon:'✦',description:"Akceptačné kritériá, regresné testy a podmienky bezpečného vydania.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35de2a9881918f4da954f65569f4",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35de2a9881918f4da954f65569f4",integrationMode:'assistant-workflow'},
 {id:'trinity-agent-coordinator',name:"Trinity Agent Coordinator",icon:'✦',description:"Rozdeľuje úlohy medzi špecialistov a zlučuje overené výsledky.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35d5a13481918481cbb6b42fbb05",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35d5a13481918481cbb6b42fbb05",integrationMode:'assistant-workflow'},
 {id:'trinity-observability-incident',name:"Trinity Observability Incident",icon:'✦',description:"Prehľad logov, health-checkov, incidentov a obnovy služieb.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35e7ad6881919f4fd2993c0d7942",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35e7ad6881919f4fd2993c0d7942",integrationMode:'assistant-workflow'},
 {id:'trinity-release-manager',name:"Trinity Release Manager",icon:'✦',description:"Plán vydania, schválenia, návrat verzie a záznamy o nasadení.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35f0d0408191b7f0c02bbd91b053",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35f0d0408191b7f0c02bbd91b053",integrationMode:'assistant-workflow'},
 {id:'trinity-business-automation',name:"Trinity Business Automation",icon:'✦',description:"Návrh obchodných automatizácií s kontrolou súhlasu a rizikových operácií.",tools:[],dependency:'Privátny ChatGPT workflow; nie je priamo spustiteľným Worker modulom',version:"1.0.0",assistantPluginId:"plugins_6aca35f93b28819198c9a121cf1fbfdb",assistantPluginUrl:"https://chatgpt.com/plugins/plugins_6aca35f93b28819198c9a121cf1fbfdb",integrationMode:'assistant-workflow'}
];
export async function pluginEnabled(env,id){
 const row=await env.DB.prepare('SELECT installed,enabled FROM ops_plugins WHERE id=?').bind(id).first();return row?.installed===1&&row?.enabled===1;
}
export async function listPlugins(env){
 const rows=(await env.DB.prepare('SELECT id,version,installed,enabled,source,installed_at,updated_at FROM ops_plugins').all()).results;
 return PLUGINS.map(p=>{const state=rows.find(r=>r.id===p.id);return {...p,version:state?.version||p.version,installed:state?.installed===1,enabled:state?.installed===1&&state?.enabled===1,source:state?.source||null,installed_at:state?.installed_at||null,updated_at:state?.updated_at||null};});
}
export async function installPlugin(env,id){
 const plugin=PLUGINS.find(item=>item.id===id);if(!plugin)throw new Error('Plugin nie je v dôveryhodnom katalógu Trinity.');
 await env.DB.prepare("INSERT INTO ops_plugins(id,version,installed,enabled,source,installed_at,updated_at) VALUES(?,?,1,1,'trinity-core',datetime('now'),datetime('now')) ON CONFLICT(id) DO UPDATE SET version=excluded.version,installed=1,enabled=1,source='trinity-core',installed_at=coalesce(ops_plugins.installed_at,datetime('now')),updated_at=datetime('now')").bind(plugin.id,plugin.version).run();
 await env.DB.prepare("INSERT INTO ops_events(action,details) VALUES('plugin_installed',?)").bind(JSON.stringify({plugin:plugin.id,source:'trinity-core'})).run();
 return {id:plugin.id,name:plugin.name,version:plugin.version,installed:true,enabled:true,source:'trinity-core'};
}
export async function ensureToolEnabled(env,tool){const p=PLUGINS.find(p=>p.tools.includes(tool));if(!p||!await pluginEnabled(env,p.id))throw new Error('Rozšírenie pre tento nástroj je vypnuté.');}
