import {z} from 'zod';
import {HttpError} from './security.js';

export const walletTransactionSchema=z.object({type:z.enum(['deposit','withdrawal','send']),amount:z.number().finite().positive().max(1000000),recipient:z.string().trim().max(120).optional(),note:z.string().trim().max(500).optional()}).strict().superRefine((value,ctx)=>{if(value.type==='send'&&!value.recipient)ctx.addIssue({code:'custom',path:['recipient'],message:'Príjemca je povinný.'});});
const money=cents=>Number((cents/100).toFixed(2));
const presentWallet=(row,transactions=[])=>({id:row.id,name:row.name,currency:row.currency,balance:money(row.balance_cents),mode:'sandbox',real_money:false,transactions:transactions.map(item=>({id:item.id,type:item.type,amount:money(item.amount_cents),balance_after:money(item.balance_after_cents),recipient:item.recipient,note:item.note,status:item.status,created_at:item.created_at}))});
async function ensureWallet(env,ownerId){let row=await env.DB.prepare('SELECT * FROM wallet_accounts WHERE owner_id=?').bind(ownerId).first();if(!row){row=await env.DB.prepare("INSERT INTO wallet_accounts(id,owner_id) VALUES(?,?) RETURNING *").bind(crypto.randomUUID(),ownerId).first();}return row;}
export async function getWallet(env,ownerId){const wallet=await ensureWallet(env,ownerId),transactions=await env.DB.prepare('SELECT * FROM wallet_transactions WHERE owner_id=? ORDER BY created_at DESC,rowid DESC LIMIT 50').bind(ownerId).all();return presentWallet(wallet,transactions.results);}
export async function transactWallet(env,ownerId,input){const data=walletTransactionSchema.parse(input),wallet=await ensureWallet(env,ownerId),amount=Math.round(data.amount*100),outgoing=data.type!=='deposit';if(outgoing&&wallet.balance_cents<amount)throw new HttpError(409,'Sandbox peňaženka nemá dostatočný virtuálny zostatok.');const next=outgoing?wallet.balance_cents-amount:wallet.balance_cents+amount,id=crypto.randomUUID();await env.DB.batch([env.DB.prepare("UPDATE wallet_accounts SET balance_cents=?,updated_at=datetime('now') WHERE id=?").bind(next,wallet.id),env.DB.prepare('INSERT INTO wallet_transactions(id,wallet_id,owner_id,type,amount_cents,balance_after_cents,recipient,note) VALUES(?,?,?,?,?,?,?,?)').bind(id,wallet.id,ownerId,data.type,amount,next,data.recipient||null,data.note||null),env.DB.prepare("INSERT INTO ops_events(action,details) VALUES('wallet_sandbox_transaction',?)").bind(JSON.stringify({id,type:data.type,amount_cents:amount,owner_id:ownerId,mode:'sandbox'}))]);return getWallet(env,ownerId);}
